### PR TITLE
Added pdo_sqlite driver support

### PR DESCRIPTION
**Pull request by vs0uz4**
pdo_sqlite driver support to include it on both 7.0 and 7.1 versions according to the request made in the PR #44

### CODE REVIEW

**Comment by hernandev** [comment]
Thanks. gonna merge and build tonight

**Comment by brunorsantos** [comment]
Hi! This Pull Request will still be merged and builded? 
Allowing us to use Sqlite in the PHP image.
Thanks!

**Comment by hernandev** [comment]
@vs0uz4 You need to specify the @php on the package name, as all the others, if you don't, the package will be installed from official repos instead of codecasts's one.

Just do this small change so I can merge it

**Comment by hernandev** [comment]
@vs0uz4 did it for you and sent a reverse pull request @ vs0uz4/ambientum/pull/1

**Comment by rogeriopradoj** [comment]
@hernandev is pdo_sqlite already available to use?

**Comment by vs0uz4** [comment]
@hernandev sorry for the delay.
was not monitoring the github and had not seen his request.
correction already done, big hug.

**Comment by hernandev** [comment]
@vs0uz4 there's a letter missing on the file, you made it `php7-pdo_sqlit@php` there's a missing `e`

Thanks

**Comment by vs0uz4** [comment]
Sorry @hernandev. 
lack of attention or typing error.

Fixed.

**Comment by mauri870** [comment]
When are you going to merge this @hernandev? I think it's ok now

**Comment by hernandev** [comment]
done, sorry for the delay guys.

please notice that: all users are encouraged to use at least PHP 7.1 now.

thank you all.

**Pull request merged**
