### PR TITLE
add php7-exif

### PR DESCRIPTION
**Pull request by joaosalless**
Hello guys,

I currently use the ambientum in some projects and need to use the exif extension in php. Do you accept this PR to include apk php7-exif?

Thank you!

### CODE REVIEW

**Comment by hernandev** [comment]
@joaosalless the Ambientum images are now using Alpine PHP builds maintained by CODECASTS itself.

So, on this repository you can check on the extensions available for install.

https://github.com/codecasts/php-alpine.

The Alpine repository is already installed on base Ambientum PHP images.

All you need to do is:

`[sudo] apk add --update php7-exif`

You can either install it eachtime or create a new image, with the extension installed.

**Comment by hernandev** [comment]
@joaosalless given the size of the package, I do not care for including it on the base image, just make a pull request on both PHP 7.0 and 7.1

**Comment by hernandev** [comment]
Haha this was a PR already, nice to see I'm really sleeping today

**Comment by hernandev** [comment]
building and publishing right away, should be available for pulling in ~20 minutes

**Comment by joaosalless** [comment]
Thank you!

**Pull request merged**
