### PR TITLE
Readme Update with Caddy Removal

### PR DESCRIPTION
**Pull request by felipyamorim**
With dropping support of Caddy (issue #58), the readme file was updated to discouraging the use of the webserver.

### CODE REVIEW

**Comment by hernandev** [comment]
@felipyamorim that's great, actually can you please just remove the caddy images from readme? it will always be on the git history but no need for it to make noise on the readme, which is already extensive.

Thanks!!!

**Comment by felipyamorim** [comment]
yes @hernandev, i will update to night.

**Comment by felipyamorim** [comment]
@hernandev, done.

**Comment by hernandev** [comment]
fixed the conflict and merged @felipyamorim thank you!

**Pull request merged**
